### ISSUE TITLE
trouble running

### ISSUE THREAD

**Issue by da-w-xu** [hlakshmi/log_collector#1]
Hi Harish!

trying to run the server and curling against it, but not getting much back.
```
dxu@K27K2J-T7Jh takehome % java --version
openjdk 21.0.2 2024-01-16
OpenJDK Runtime Environment Homebrew (build 21.0.2)
OpenJDK 64-Bit Server VM Homebrew (build 21.0.2, mixed mode, sharing)
```

```
dxu@K27K2J-T7Jh log_collector % java -cp target/log_collector-1.0-SNAPSHOT.jar com.log_collector.java.LogCollectorServer

Started server on port 8000
```

```
dxu@K27K2J-T7Jh takehome % curl -vvv -X POST http://localhost:8000 -H "Content-Type: application/json" -d '{ "filename": "/var/log/install.log", "num_lines": 10, "keywords": [ "2024" ] }'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying [::1]:8000...
* Connected to localhost (::1) port 8000
> POST / HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/8.4.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 79
>
* Empty reply from server
* Closing connection
curl: (52) Empty reply from server
```

i tried a few different things and payloads, always getting empty reply. any more instructions you can add to the README?

**Comment by hlakshmi** [comment]
Hi Da, 
I will check it out on why it was not running and let you know what's causing the problem. 
I did test the end-to-end via Postman (I don't think that should make a difference too) and it worked fine for me. Infact I tested with large files which are in GB's too.

Anyway I will keep you posted. Thanks for checking.

**Comment by hlakshmi** [comment]
@da-w-xu - I have checked the issue and it seems like the dependencies are not included in JAR file correctly when building it. I have corrected the pom.xml file and committed a latest version of it. I have tested it and made it works as expected.
Apologies for the issue.

Can you pull the latest and run the following:
```
mvn clean compile assembly:single
java -cp target/log_collector-1.0-SNAPSHOT-jar-with-dependencies.jar com.log_collector.java.LogCollectorServer
```
Thanks,
Harish.
